"""Pure, app-independent GUI configuration model, inheritance, and codec."""

from .codec import SessionCodecError, raw_to_schema, schema_to_raw
from .inheritance import (
    align_locked_literals,
    inherit_from,
    make_default_value,
    select_ref_value_spec,
)
from .lowering import (
    ExpressionResolver,
    RangeFactory,
    ReferenceResolver,
    lower_finished_cfg,
    validate_finished_cfg,
    validate_reference_kinds,
)
from .model import (
    CenteredSweepSpec,
    CenteredSweepValue,
    CfgNodeSpec,
    CfgNodeValue,
    CfgSchema,
    CfgSectionSpec,
    CfgSectionValue,
    ChoiceBinding,
    ChoiceSectionSpec,
    DirectValue,
    EvalValue,
    FloatSpec,
    IntSpec,
    LiteralSpec,
    ReferenceSpec,
    ReferenceValue,
    ScalarLeafInput,
    ScalarSpec,
    ScalarValue,
    SweepSpec,
    SweepValue,
    default_value_for_type,
)

__all__ = [
    "CenteredSweepSpec",
    "CenteredSweepValue",
    "CfgNodeSpec",
    "CfgNodeValue",
    "CfgSchema",
    "CfgSectionSpec",
    "CfgSectionValue",
    "ChoiceBinding",
    "ChoiceSectionSpec",
    "DirectValue",
    "EvalValue",
    "ExpressionResolver",
    "FloatSpec",
    "IntSpec",
    "LiteralSpec",
    "ReferenceSpec",
    "ReferenceValue",
    "RangeFactory",
    "ReferenceResolver",
    "ScalarLeafInput",
    "ScalarSpec",
    "ScalarValue",
    "SessionCodecError",
    "SweepSpec",
    "SweepValue",
    "align_locked_literals",
    "default_value_for_type",
    "inherit_from",
    "lower_finished_cfg",
    "make_default_value",
    "raw_to_schema",
    "schema_to_raw",
    "select_ref_value_spec",
    "validate_finished_cfg",
    "validate_reference_kinds",
]
