"""Pure, app-independent GUI configuration model, inheritance, and codec."""

from .codec import SessionCodecError, decode_eval_wire, raw_to_schema, schema_to_raw
from .inheritance import (
    align_locked_literals,
    inherit_from,
    make_default_value,
    select_ref_value_spec,
)
from .lowering import (
    ExpressionResolver,
    RangeFactory,
    ReferenceResolver,
    lower_finished_cfg,
    validate_finished_cfg,
    validate_reference_kinds,
)
from .materialization import (
    RAW_MISSING,
    RawMissing,
    ReferenceMaterialization,
    SpecMaterializationPolicy,
    materialize_spec_value,
)
from .model import (
    CenteredSweepSpec,
    CenteredSweepValue,
    CfgNodeSpec,
    CfgNodeValue,
    CfgSchema,
    CfgSectionSpec,
    CfgSectionValue,
    ChoiceBinding,
    ChoiceSectionSpec,
    DirectValue,
    EvalValue,
    FloatSpec,
    IntSpec,
    LiteralSpec,
    ReferenceSpec,
    ReferenceValue,
    ScalarLeafInput,
    ScalarSpec,
    ScalarValue,
    SweepSpec,
    SweepValue,
    default_value_for_type,
)
from .reference_key import (
    is_custom_reference_key,
    make_custom_reference_key,
    parse_custom_reference_key,
)
from .schema_assembler import (
    USE_SPEC_DEFAULT,
    CfgSchemaAssembler,
    default_value_for_spec,
)
from .tree import read_value_path, replace_value_path, resolve_spec_path

__all__ = [
    "CenteredSweepSpec",
    "CenteredSweepValue",
    "CfgNodeSpec",
    "CfgNodeValue",
    "CfgSchema",
    "CfgSchemaAssembler",
    "CfgSectionSpec",
    "CfgSectionValue",
    "ChoiceBinding",
    "ChoiceSectionSpec",
    "DirectValue",
    "EvalValue",
    "ExpressionResolver",
    "FloatSpec",
    "IntSpec",
    "LiteralSpec",
    "ReferenceSpec",
    "ReferenceValue",
    "RangeFactory",
    "RAW_MISSING",
    "RawMissing",
    "ReferenceMaterialization",
    "ReferenceResolver",
    "ScalarLeafInput",
    "ScalarSpec",
    "ScalarValue",
    "SessionCodecError",
    "SweepSpec",
    "SweepValue",
    "SpecMaterializationPolicy",
    "USE_SPEC_DEFAULT",
    "align_locked_literals",
    "default_value_for_type",
    "decode_eval_wire",
    "default_value_for_spec",
    "inherit_from",
    "is_custom_reference_key",
    "lower_finished_cfg",
    "make_default_value",
    "materialize_spec_value",
    "make_custom_reference_key",
    "parse_custom_reference_key",
    "raw_to_schema",
    "read_value_path",
    "replace_value_path",
    "resolve_spec_path",
    "schema_to_raw",
    "select_ref_value_spec",
    "validate_finished_cfg",
    "validate_reference_kinds",
]
