"""GUI adapter package — contracts, types, lowering, and inheritance helpers."""

from .analyze_params import ParamMeta, reconstruct_params
from .inheritance import inherit_from, make_default_value
from .lowering import _find_allowed_spec, _section_to_dict, schema_to_dict
from .protocol import (
    AbsExpAdapter,
    NoAnalysisAdapterMixin,
    NoAnalysisResult,
    NoAnalyzeParams,
)
from .types import (
    AdapterCapabilities,
    AnalyzeRequest,
    AnalyzeResultWithFigure,
    CfgNodeSpec,
    CfgNodeValue,
    CfgSchema,
    CfgSectionSpec,
    CfgSectionValue,
    ContextReadiness,
    DeviceRefSpec,
    DirectValue,
    EvalValue,
    ExpContext,
    ExperimentProtocol,
    LiteralSpec,
    MetaDictWriteback,
    ModuleRefSpec,
    ModuleRefValue,
    ModuleWriteback,
    MultiSweepSpec,
    MultiSweepValue,
    RunRequest,
    SaveDataRequest,
    SavePaths,
    ScalarSpec,
    ScalarValue,
    SocCfgHandle,
    SocCfgProtocol,
    SocHandle,
    SocProtocol,
    SweepSpec,
    SweepValue,
    T_AnalyzeParams,
    T_AnalyzeResult,
    T_Cfg,
    T_Result,
    WaveformRefSpec,
    WaveformRefValue,
    WaveformWriteback,
    WritebackItem,
    WritebackRequest,
    default_value_for_type,
)
from .validation import require_soc_handles
