"""GUI adapter package — contracts, types, lowering, and inheritance helpers."""

from .inheritance import inherit_from, make_default_value
from .lowering import _find_allowed_spec, _section_to_dict, schema_to_dict
from .protocol import AbsExpAdapter
from .types import (
    AnalyzeParam,
    AnalyzeRequest,
    AnalyzeResultWithFigure,
    CfgNodeSpec,
    CfgNodeValue,
    CfgSchema,
    CfgSectionSpec,
    CfgSectionValue,
    DirectValue,
    EvalValue,
    ExpContext,
    LiteralSpec,
    MetaDictWriteback,
    ModuleRefSpec,
    ModuleRefValue,
    ModuleWriteback,
    MultiSweepSpec,
    MultiSweepValue,
    RunRequest,
    SaveDataRequest,
    SavePaths,
    ScalarSpec,
    ScalarValue,
    SocCfgHandle,
    SocHandle,
    SweepSpec,
    SweepValue,
    T_AnalyzeResult,
    T_Result,
    WaveformRefSpec,
    WaveformRefValue,
    WaveformWriteback,
    WritebackItem,
    WritebackRequest,
    analyze_params_to_raw_dict,
)

__all__ = [
    "AbsExpAdapter",
    "AnalyzeParam",
    "AnalyzeRequest",
    "AnalyzeResultWithFigure",
    "CfgNodeSpec",
    "CfgNodeValue",
    "CfgSchema",
    "CfgSectionSpec",
    "CfgSectionValue",
    "DirectValue",
    "EvalValue",
    "ExpContext",
    "LiteralSpec",
    "MetaDictWriteback",
    "ModuleRefSpec",
    "ModuleRefValue",
    "ModuleWriteback",
    "MultiSweepSpec",
    "MultiSweepValue",
    "RunRequest",
    "SaveDataRequest",
    "SavePaths",
    "ScalarSpec",
    "ScalarValue",
    "SocCfgHandle",
    "SocHandle",
    "SweepSpec",
    "SweepValue",
    "T_AnalyzeResult",
    "T_Result",
    "WaveformRefSpec",
    "WaveformRefValue",
    "WaveformWriteback",
    "WritebackItem",
    "WritebackRequest",
    "analyze_params_to_raw_dict",
    "inherit_from",
    "make_default_value",
    "schema_to_dict",
    "_find_allowed_spec",
    "_section_to_dict",
]
