"""GUI adapter package — contracts, types, lowering, and inheritance helpers."""

from .analyze_params import ParamMeta, describe_analyze_params, reconstruct_params
from .inheritance import inherit_from, make_default_value
from .lowering import find_allowed_spec
from .protocol import ExpAdapterProtocol
from .types import (
    AdapterCapabilities,
    AdapterGuide,
    AnalysisMode,
    AnalyzeRequest,
    AnalyzeResultBase,
    AnalyzeResultWithFigure,
    CfgNodeSpec,
    CfgNodeValue,
    CfgSchema,
    CfgSectionSpec,
    CfgSectionValue,
    ContextReadiness,
    DeviceRefSpec,
    DirectValue,
    EvalValue,
    ExpContext,
    ExperimentProtocol,
    FloatSpec,
    InteractiveHost,
    InteractiveSession,
    IntSpec,
    LiteralSpec,
    MetaDictWriteback,
    ModuleRefSpec,
    ModuleRefValue,
    ModuleWriteback,
    NoAnalysisResult,
    NoAnalyzeParams,
    RunRequest,
    SaveDataRequest,
    SavePaths,
    ScalarLeafInput,
    ScalarSpec,
    ScalarValue,
    SocCfgHandle,
    SocCfgProtocol,
    SocHandle,
    SocProtocol,
    SweepSpec,
    SweepValue,
    T_AnalyzeParams,
    T_AnalyzeResult,
    T_Cfg,
    T_Result,
    WaveformRefSpec,
    WaveformRefValue,
    WaveformWriteback,
    WritebackItem,
    WritebackRequest,
    default_value_for_type,
)
from .validation import require_soc_handles
